"""
headings # heading1 ## heading2

bold **text**

italic *text*

lists
- item1
- item2

links [text](URL)

"""

import markdown

def read_markdown_file(file_path):
	with open(file_path, 'r') as file:
		return file.read()
	
def convert_markdown_to_html(markdown_text):
	return markdown.markdown(markdown_text)

def wrap_inHtml_template(content):
	html_template = f"""
	<!DOCTYPE html>
	<html lang="en">
	<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Markdown Conversion</title>
    <style>
		/* Reset and base styles */
		*, *::before, *::after {{
            box-sizing: border-box;
			margin: 0;
			padding: 0;
        }}
        body {{
			font-family: Helvetica, Arial, sans-serif;
            line-height: 1.6;
			background: #fafafa;
			color: #222;
			padding: 1rem;
        }}
		header, footer {{
			background: #333;
			color: #fff;
            text-align: center;
			padding: 1rem 0;
        }}
        main {{
            max-width: 800px;
			margin: 2rem auto;
			background: #fff;
			padding: 2rem;
            border-radius: 8px;
			box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }}
		/* Simple responsive typography */
		h1, h2, h3, h4, h5, h6 {{
			margin-bottom: 0.5rem;
			line-height: 1.2;
        }}
		p {{
			margin-bottom: 1rem;
        }}
    </style>
	</head>
	<body>
		<header><h1>Document</h1></header>
		<main>
			{content}
		</main>
		<footer><p>Generated by Markdown to HTML Converter</p></footer>
	</body>
	</html>
	"""
	return html_template

def write_html_file(html_content, output_path):
	with open(output_path, 'w') as file:
		file.write(html_content)

def main():
	print("Welcome to the Markdown to HTML Converter!")

	markdown_file = input("Enter the path to your Markdown file: ")
	html_output_file = input("Enter the desired output path for the HTML file: ")

	try:
		markdown_text = read_markdown_file(markdown_file)
		html_content = convert_markdown_to_html(markdown_text)
		html_with_template = wrap_inHtml_template(html_content)
		write_html_file(html_with_template, html_output_file)
		print(f"Successfully converted '{markdown_file}' to '{html_output_file}'!")
	except Exception as e:
		print(f"An error occurred: {e}")

if __name__ == "__main__":
	main()